COMPILER ?= $(GCC_PATH)gcc
FLAGS ?= -O3 -Wall -fopenmp $(GCC_SUPPFLAGS) #-DDEBUG

LDFLAGS ?= -g -fopenmp
LDLIBS = -lm

EXECUTABLE = omp_merge_sort 

SRCS=$(wildcard src/*.c)
OBJS=$(SRCS:src/%.c=obj/%.o)

all: $(OBJS)
	$(COMPILER) $(LDFLAGS) -o $(EXECUTABLE) $(OBJS) $(LDLIBS) 

obj/%.o: src/%.c | obj
	$(COMPILER) $(FLAGS) -o $@ -c $<

#create the obj directory if it does not exist
obj:
	mkdir -p $@

clean:
	rm -f obj/* *.log
	rm $(EXECUTABLE) 
