/**
 * @file    errmsg.h
 * @brief   Error messages for the ALAN-2022 parser.
 * @author  W. H. K. Bester (whkbester@cs.sun.ac.za)
 * @date    2022-08-03
 */

#ifndef ERRMSG_H
#define ERRMSG_H

typedef enum {
	ERR_ARRAY_ALLOCATION_OR_EXPRESSION_EXPECTED,
	ERR_EXPECT,
	ERR_EXPRESSION_OR_STRING_EXPECTED,
	ERR_FACTOR_EXPECTED,
	ERR_ILLEGAL_ARRAY_OPERATION,
	ERR_LEAVE_EXPRESSION_NOT_ALLOWED_FOR_PROCEDURE,
	ERR_MISSING_LEAVE_EXPRESSION_FOR_FUNCTION,
	ERR_MULTIPLE_DEFINITION,
	ERR_NOT_A_FUNCTION,
	ERR_NOT_AN_ARRAY,
	ERR_NOT_A_PROCEDURE,
	ERR_NOT_A_VARIABLE,
	ERR_SCALAR_EXPECTED,
	ERR_STATEMENT_EXPECTED,
	ERR_TOO_FEW_ARGUMENTS,
	ERR_TOO_MANY_ARGUMENTS,
	ERR_TYPE_EXPECTED,
	ERR_UNKNOWN_IDENTIFIER,
	ERR_UNREACHABLE
} Error;

#endif /* ERRMSG_H */
